---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata: null
name: cleanup
spec: null
description: This task will clean up a workspace by deleting all the files.
workspaces:
  - name: source
steps:
  - name: remove
    image: alpine:3
    env:
      - name: WORKSPACE_SOURCE_PATH
        value: $(workspaces.source.path)
    workingDir: $(workspaces.source.path)
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
    script: >
      #!/usr/bin/env sh

      set -eu

      echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."

      # Delete any existing contents of the directory if it exists.

      #

      # We don't just "rm -rf ${WORKSPACE_SOURCE_PATH}" because ${WORKSPACE_SOURCE_PATH} might be "/"

      # or the root of a mounted volume.